Adding touch event to icon
Rmano/gse-touchpad-onoff pull request #2
Opened 2024-01-10 05:13 UTC by corebots

For laptops with a touchscreen and those situation when one gets stuck with an inactive touchpad, being able to toggle the touchpad by tapping the icon on the screen seems handy. Tested on a Dell XPS 13 Plus Touchscreen, seems to work fine!

2024-01-10 05:15 UTC, corebots commented
Hello! I've added a line to enable touch events. Hope this is the correct way. Also, I'm new to contributions by a PR. If I'm doing it wrongly, please ignore or provide some feedback when you get time for it. Thanks!

2024-01-10 07:52 UTC, Rmano requested changes
Almost! 

You need to use another connection Id (for example: `this.touchId = ...` and then do the appropriate disconnection in `disable()`, similar to the other ones: 

https://github.com/Rmano/gse-touchpad-onoff/blob/2a071eef612ef42be08a6dfcd06f0fd882c6254e/TouchpadOnOff%40romano.rgtti.com/extension.js#L91-L93

2024-01-15 19:12 UTC, Rmano approved these changes

2024-01-15 19:13 UTC, Rmano commented
Hi @corebots , I did the change myself. If you're ok, I'll merge...

2024-01-16 17:51 UTC, Rmano commented
Hmmm.... @corebots , did you try it? It does not work on my laptop. I think that it takes the "touch-event" and then immediately a "click-event", and so it does not change.

2024-12-22 18:36 UTC, closed without merging

2024-12-22 18:36 UTC, Rmano commented
Closing, #3 fixed the double bounce problem. Thanks anyway!